# Generated by Django 5.0.2 on 2024-03-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.TextField()),
                ('recipe_description', models.CharField(max_length=1500)),
                ('recipe_file', models.FileField(upload_to='recipe_images')),
            ],
        ),
    ]
