# Generated by Django 5.0.2 on 2024-03-27 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_recipemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipemodel',
            name='recipe_name',
        ),
    ]
