# Generated by Django 5.0.2 on 2024-03-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_recipemodel_recipe_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipemodel',
            name='recipe_name',
            field=models.TextField(null=True),
        ),
    ]
