# Generated by Django 5.0.2 on 2024-04-15 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_department_student_uid_remove_student_rollno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_uid',
            name='uid',
            field=models.CharField(max_length=20),
        ),
    ]
